STENO_ENABLE = yes
STENO_PROTOCOL = geminipr

OLED_ENABLE = yes
ENCODER_MAP_ENABLE = no
BACKLIGHT_ENABLE = no

# Reduce compiled size
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
